###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/635e7ef03656b7eec4e9b644

###

POST http://localhost:3000/post
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWEyM2UxZjkzMmZkMDM5MWQzM2IzMCIsImlhdCI6MTY3NjI5NTk1MiwiZXhwIjoxNjc2Mjk2NDUyfQ.ccMoWLts6-fkrr-0q1GLDzDYxt1TFZ8_Y_U6_tdRz7A

{
    "message": "jacobelbaz@outlook.fr",
    "sender": "12345678",
    "photo" : "jfsnefsjeknfdkejwnd.jpeg"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456"
}

###